-- Reference Data: Nature Types (CDTIPODATO = 110)
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('110', 'U', 'Urbano', 'Bien Inmueble Urbano');
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('110', 'R', 'Rústico', 'Bien Inmueble Rústico');
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('110', 'V', 'Vehículo', 'Vehículo');
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('110', 'C', 'Cuenta', 'Cuenta Bancaria');
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('110', 'A', 'Actividad', 'Actividad Empresarial');
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('110', 'T', 'Otros', 'Otros Bienes');
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('110', 'N', 'Val.No Neg.', 'Valores No Negociados');

-- Reference Data: Position Types (CDTIPODATO = 104)
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('104', 'P', 'Pleno', 'Pleno Dominio');
INSERT INTO GATA_DATOGENA (CDTIPODATO, CDDATOGENA, DSABREV, DSDATOGENA) VALUES ('104', 'G', 'Ganancial', 'Ganancial');

-- Provinces
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('01', 'Álava');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('02', 'Albacete');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('03', 'Alicante');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('04', 'Almería');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('05', 'Ávila');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('06', 'Badajoz');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('07', 'Baleares');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('08', 'Barcelona');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('09', 'Burgos');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('10', 'Cáceres');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('11', 'Cádiz');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('12', 'Castellón');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('13', 'Ciudad Real');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('14', 'Córdoba');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('15', 'A Coruña');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('16', 'Cuenca');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('17', 'Girona');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('18', 'Granada');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('19', 'Guadalajara');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('20', 'Guipúzcoa');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('21', 'Huelva');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('22', 'Huesca');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('23', 'Jaén');
INSERT INTO SUCA_PROVINCIA (CDPROV, DSPROV) VALUES ('24', 'León');
INSERT